"""adds fk to usergoals table

Revision ID: 1e35b9b8bf61
Revises: 1f8719c57263
Create Date: 2024-03-20 11:49:17.776549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e35b9b8bf61'
down_revision = '1f8719c57263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_user_goals_goal_id_goals'), 'goals', ['goal_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_goals', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_goals_goal_id_goals'), type_='foreignkey')
        batch_op.drop_column('goal_id')

    # ### end Alembic commands ###
