"""adds fk to authuser class

Revision ID: 66f828eadfbd
Revises: 422382df587f
Create Date: 2024-03-27 16:26:52.678060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66f828eadfbd'
down_revision = '422382df587f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userId', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_auth_users_userId_users'), 'users', ['userId'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_auth_users_userId_users'), type_='foreignkey')
        batch_op.drop_column('userId')

    # ### end Alembic commands ###
