"""removes null from date in user goal;


Revision ID: e92618ba79e3
Revises: 47e24f7d5a69
Create Date: 2024-03-21 13:25:36.626096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e92618ba79e3'
down_revision = '47e24f7d5a69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_goals', schema=None) as batch_op:
        batch_op.alter_column('completed_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_goals', schema=None) as batch_op:
        batch_op.alter_column('completed_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
